export const AUTH_START  = "AUTH_START";
export const AUTH_SUCCESS  = "AUTH_SUCCESS";
export const AUTH_LOGOUT  = "AUTH_LOGOUT";
export const AUTH_FAIL  = "AUTH_FAIL";

export const NEWS_FETCH_START = "NEWS_FETCH_START";
export const NEWS_FETCH_SUCCESS = "NEWS_FETCH_SUCCESS";
export const NEWS_FETCH_FAIL = "NEWS_FETCH_FAIL";
export const UPDATES_FETCH_SUCCESS = "UPDATES_FETCH_SUCCESS";

export const STATS_FETCH_START = "STATS_FETCH_START";
export const STATS_FETCH_SUCCESS = "STATS_FETCH_SUCCESS";
export const STATS_FETCH_FAIL = "STATS_FETCH_FAIL";
export const WORLD_TABLE_FETCH_SUCCESS = "WORLD_TABLE_FETCH_SUCCESS";
export const TABLE_DATA_FETCH_SUCCESS = 'TABLE_DATA_FETCH_SUCCESS';

export const MAP_FETCH_START = 'MAP_FETCH_START';
export const MAP_FETCH_FAIL = 'MAP_FETCH_FAIL';
export const MAP_FETCH_SUCCESS = 'MAP_FETCH_SUCCESS';