# Generated by Django 3.0.5 on 2020-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200410_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('href', models.URLField()),
            ],
        ),
    ]
