# Generated by Django 3.0.5 on 2020-04-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200421_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidNews',
        ),
    ]
