# Generated by Django 3.0.5 on 2020-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_covidnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidnews',
            name='date',
            field=models.DateField(),
        ),
    ]
