# Generated by Django 3.0.5 on 2020-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200421_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidnews',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
