# Generated by Django 3.0.5 on 2020-04-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200421_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidnews',
            options={'verbose_name_plural': 'Covid News'},
        ),
    ]
