# Generated by Django 3.0.5 on 2020-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200426_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaCovidStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('total_case', models.CharField(max_length=20)),
                ('new_case', models.CharField(max_length=20)),
                ('total_death', models.CharField(max_length=20)),
                ('new_death', models.CharField(max_length=20)),
                ('total_recovered', models.CharField(max_length=20)),
                ('active_case', models.CharField(max_length=20)),
                ('serious_critical', models.CharField(max_length=20)),
                ('cases_per_million', models.CharField(max_length=20)),
                ('deaths_per_million', models.CharField(max_length=20)),
                ('total_test', models.CharField(max_length=20)),
                ('test_per_million', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCovidStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('total_case', models.CharField(max_length=20)),
                ('new_case', models.CharField(max_length=20)),
                ('total_death', models.CharField(max_length=20)),
                ('new_death', models.CharField(max_length=20)),
                ('total_recovered', models.CharField(max_length=20)),
                ('active_case', models.CharField(max_length=20)),
                ('serious_critical', models.CharField(max_length=20)),
                ('cases_per_million', models.CharField(max_length=20)),
                ('deaths_per_million', models.CharField(max_length=20)),
                ('total_test', models.CharField(max_length=20)),
                ('test_per_million', models.CharField(max_length=20)),
            ],
        ),
    ]
