# Generated by Django 3.0.5 on 2020-04-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_indiacovidstats_worldcovidstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcovidstats',
            name='serious_critical',
        ),
        migrations.RemoveField(
            model_name='worldcovidstats',
            name='test_per_million',
        ),
        migrations.RemoveField(
            model_name='worldcovidstats',
            name='total_test',
        ),
    ]
