# Generated by Django 3.0.5 on 2020-04-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200426_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldcovidstats',
            options={'ordering': ['-total_case']},
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='active_case',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='cases_per_million',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='deaths_per_million',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='new_case',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='new_death',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='total_case',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='total_death',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldcovidstats',
            name='total_recovered',
            field=models.FloatField(),
        ),
    ]
