# Generated by Django 3.0.5 on 2020-04-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200426_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidnews',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Covid News'},
        ),
    ]
