# Generated by Django 3.0.5 on 2020-04-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200429_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCountryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChinaCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='FranceCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='GermanyCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='IranCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='ItalyCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='RussiaCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='SpainCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='TurkeyCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='UKCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='UkraineCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
        migrations.CreateModel(
            name='UsCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
    ]
