# Generated by Django 3.0.5 on 2020-04-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_basecountrystats_chinacovidstats_francecovidstats_germanycovidstats_irancovidstats_italycovidstats_r'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndiaCovidStats',
            new_name='IndiaFullCovidStats',
        ),
    ]
