# Generated by Django 3.0.5 on 2020-04-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200429_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
            ],
            bases=('core.basecountrystats',),
        ),
    ]
