# Generated by Django 3.0.5 on 2020-05-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_indiacovidstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indiafullcovidstats',
            options={'ordering': ['state']},
        ),
        migrations.RenameField(
            model_name='indiafullcovidstats',
            old_name='city',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='active_case',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='cases_per_million',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='deaths_per_million',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='new_case',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='new_death',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='serious_critical',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='test_per_million',
        ),
        migrations.RemoveField(
            model_name='indiafullcovidstats',
            name='total_test',
        ),
    ]
