# Generated by Django 3.0.5 on 2020-05-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200501_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaCovid19Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('href', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
