# Generated by Django 3.0.6 on 2020-05-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_indiacovid19update'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldMapCovidStats',
            fields=[
                ('basecountrystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseCountryStats')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
            ],
            bases=('core.basecountrystats',),
        ),
    ]
