# Generated by Django 3.0.6 on 2020-05-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_worldmapcovidstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldmapcovidstats',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldmapcovidstats',
            name='lon',
            field=models.FloatField(),
        ),
    ]
