# Generated by Django 3.0.6 on 2020-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200508_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiafullcovidstats',
            name='total_case',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='indiafullcovidstats',
            name='total_death',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='indiafullcovidstats',
            name='total_recovered',
            field=models.IntegerField(),
        ),
    ]
