# Generated by Django 3.0.6 on 2020-05-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200508_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecountrystats',
            options={'ordering': ['date']},
        ),
    ]
