# Generated by Django 3.0.6 on 2020-05-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_covid19query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19query',
            name='reply',
            field=models.TextField(default='We Will Reply You Soon'),
        ),
        migrations.CreateModel(
            name='Covid19QueryReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Replies to Covid19 Queries',
                'ordering': ['-posted_at'],
            },
        ),
    ]
