# Generated by Django 3.0.6 on 2020-05-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200513_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid19QueryReplies',
        ),
    ]
